name: Deploy final project
on:
   push:
      branches: 
         - main
jobs:
    deploy:
        runs-on: uubuntu-latest
        steps:
           - name: Deploy to EC2 server
             uses: appleboy/ssh-action@v1
             with:
              host: ${{ secrets.HOST }}
              username: ubuntu
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                    cd final_project
                    git pull
                    docker build -t final_app .
                    docker stop app || true
                    docker rm app || true
                    docker run -d -p 8080:80 --name app final_app
